[2024-01-24T01:06:50.071+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.get_account scheduled__2024-01-23T23:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-01-24T01:08:35.832+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.get_account scheduled__2024-01-23T23:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-01-24T01:09:49.139+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.get_account scheduled__2024-01-23T23:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-01-24T01:16:59.389+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.get_account scheduled__2024-01-23T23:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
