[2024-01-23T23:37:51.968+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.is_valid scheduled__2024-01-23T22:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-01-23T23:38:53.489+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.is_valid scheduled__2024-01-23T22:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-01-23T23:40:24.031+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.is_valid scheduled__2024-01-23T22:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
